shop_pro/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.carrinho_detalhe, name='carrinho_detalhe'),
    path('add/<int:produto_id>/',views.carrinho_adicionar, name='carrinho_adicionar'),
    path('remover/<int:produto_id>/',views.carrinho_remove, name='carrinho_remover'),
]

shop_pro/shop_app/urls.py
from django.urls import path
from .import views

app_name = "shop_app"

urlpatterns = [
    path('',views.lista_produto, name ='lista_produto'),
    path('<slug:categoria_slug>/',views.lista_produto,name='lista_produto_by_categoria'),
    path('<int:id>/<slug:slug>/',views.detalhe_produto,name='detalhe_produto'),
]

shop_pro/shop_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carrinho/', include('cart.urls',namespace='carrinho')),
    path('',include('shop_app.urls',namespace='shop_app')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop_pro/cart/models.py
from django.db import models

# Create your models here.

shop_pro/encomendas/models.py
from django.db import models
from shop_app.models import Produto

# Create your models here.

class Encomenda(models. Model):
    primeiro_nome = models.CharField(max_length=50)
    ultimo_nome   = models.CharField(max_length=50)
    email         = models.EmailField()
    endereco      = models.CharField(max_length=250)
    cep           = models.CharField(max_length=20)
    cidade        = models.CharField(max_length=100)
    criado        = models.DateTimeField(auto_now_add=True)
    atualizado    = models.BooleanField(auto_now=True)
    pago          = models.BooleanField(default=False)

    class Meta:
        encomendando = ('-criado',)

    def __str__(self):
        return f'Encomenda {self.id}'

    def get_custo_total(self):
        return sum(item.get_custo() for item in self.items.all())

class EncomendarItem(models.Model):
    encomenda = models.ForeignKey(Encomenda,
                                  nome_relacionado='items',
                                  on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto,
                                nome_relacionado='encomendar_items',
                                on_delete=models.CASCADE)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_custo(self):
        return self.preco * self.quantidade

shop_pro/shop_app/models.py
from django.db import models
from django.urls import reverse

class Categoria(models.Model):
    nome = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ('nome',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:lista_produto_by_category',args=[self.slug])

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='produtos',on_delete=models.CASCADE)
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    imagem = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    descricao = models.TextField(blank=True)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    disponivel = models.BooleanField(default=True)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('nome',)
        index_together = (('id', 'slug'),)

    def __str_(self):
        return self.name

    def get_absolute_url(selg):
        return reverse('shop:detalhe_produto',args=[self.id, self.slug])

# Create your models here.

shop_pro/cart/forms.py
from django import forms

ESCOLHA_QUANTIDADE_PRODUTOS = [(i, str(i)) for i in range(1, 21)]

class AdicionaProdutoCarrinhoForm(forms.Form):
    quantidade = forms.TypedChoiceField(
                                escolhas= ESCOLHA_QUANTIDADE_PRODUTOS,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

shop_pro/cart/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop_app.models import Produto
from .cart import Carrinho
from .forms import AdicionaProdutoCarrinhoForm

# Create your views here.

@requirea_POST
def cart_add(request, product_id):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=produto_id)
    form = AdicionaProdutoCarrinhoForm(request.POST)
    if form.is_valid():
        cd = form.claned_data
        carrinho.add(produto=produto,
                     quantidade=cd['quantidade'],
                     override_quantidade=cd['override'])
    return redirect('carrinho:carrinho_detalhe')

@require_POST
def carrinho_remove(request, produto_id):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=produto_id)
    carrinho.remove(produto)
    return redirect('carrinho:carrinho_detalhe')

def carrinho_detalhe(request):
    carrinho = carrinho(request)
    return render(request,'carrinho/detalhe.html',{'carrinho':carrinho})

shop_pro/encomendas/views.py
from django.shortcuts import render

# Create your views here.

shop_pro/shop_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Categoria, Produto
from .forms import AdicionaProdutoCarrinhoForm

#
# Create your views here.
# Create your views here.

def lista_produto(request, categoria_slug=None):
    categoria = None
    categorias = Categoria.objects.all()
    produto = Produto.objects.filter(disponivel=True)

    if categoria_slug:
        categoria = get_object_or_404(Categoria, slug=categoria_slug)
        produtos = produtos.filter(categoria=categoria)
    return render(request,'shop/produto/lista.html',
                         {'categoria':categoria,
                         'categorias':categorias,
                         'produto':produto})

def detalhe_produto(request, id, slug):
    produto = get_object_or_404(Produto,
                                id=id,
                                slug=slug,
                                disponivel=True)
    carrinho_produto_form =  AdicionaProdutoCarrinhoForm()
    return render(request,'shop/produto/detalhe.html',
                           {'produto':produto
                            'carrinho_produto_form' : carrinho_produto_form})

shop_pro/cart/templates/carrinho/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Seu carrinho de compras
{% endblock %}

{% block content %}
  <h1>Seu carrinho de compras</h1>
  <table class="carrinho">
    <thead>
      <tr>
        <th>Imagem</th>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Remover</th>
        <th>Preço unitário</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with produto=item.produto %}
          <tr>
            <td>
              <a href="{{ produto.get_absolute_url }}">
                <img src="{% if produto.imagem %} {{ produto.imagem.url}}
                {% else %} {% static "img/no_img.png"%} {% endif %}">
              </a>
            </td>
            <td>{{ produto.nome }}</td>
            <td>{{ item.quantidade }}</td>
            <td>
              <form action="{% url "carrinho:carrinho_remove" produto.id %}" method="post">

                <input type="submit" value="Remove">
                {% csrf_token%}
              </form>
            </td>
            <td class="num">${{ item.preco }}</td>
            <td class="num">${{ item.ottal_price }}</td>
          </tr>
          {% endwith %}
        {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">${{ carrinho.get_total_price }}</td>
        </tr>
      </tbody>
  </table>
  <p class="text-rigt">
    <a href="{% url "shop_app:produto_lista" %}" class="button light">Continue shoping</a>
    <a href="#" class="button">Checkout</a>
  </p>
  {% endblock %}

shop_pro/shop_app/templates/shop/base.html
{% load static %}
<!DOCTYPE html>

<html lang="pt" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>{% block title %}Meu Shop 3D{% endblock %}</title>

  </head>

  <body>

    <div id="header">
      <a href="/" class="logo">Meu Shop 3D</a>
    </div>

    <div class="cart">
      {% with total_items=cart | length %}
        {% if total_items > 0 %}
          Seu carrinho:
        <a href="{% url "cart:cart_detail" %}">
          {{ total_items }}item{{ total_items|pluralize }},
          ${{ cart.get_total_price }}
        </a>
        {% else %}
          Seu carrinho está vazio.
        {% endif %}
      {% endwith %}
    </div>

    <div id="content">
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>

shop_pro/shop_app/templates/shop/produto/detalhe.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
<div class="product-detail">
  <img src="{% if product.image %}{{ product.image.url }}{% else %}
  {% static "imfg/no_image.png" %}{% endif %}">
  <h1>{{ product.name }}</h1>
  <h2>
    <a href="{{ product.category.get_absolute_url }}">
      {{ product.category }}
    </a>
  </h2>
  <p class="price">${{ product.price }}</p>
  <form action="{% url "carrinho_adiciona" produto.id %}" method="post">
    {{ carrinho_produto_form }}
    {% csrf_token %}
    <input type = "submit" value="Adcicionar ao carrinho">
    </form>
    {{ produto.description|linebraks }}
</div>
{% endblock %}

shop_pro/shop_app/templates/shop/produto/lista.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if categoria %}{{ categoria.name }}{% else %}Produtos{% endif %}
{% endblock %}

{% block content %}

  <div id="sidebar">

    <h3>Catagoria</h3>

    <ul>

      <li {% if not categoria %}class="selected"{% endif %}>
        <a href="{% url "shop_app:lista_produto" %}">Tudo</a>
      </li>

      {% for c in categoria %}

        <li {% if categoria.slug == c.slug %}class="selected">
        {% endif %}
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>

      {% endfor %}
    </ul>
    </div>

    <div id="main" class="lista_produto">
      <h1>{% if categoria %}{{ categoria.name }} {% else %}produtos
      {% endif %}</h1>
      {% for produto in produtos %}
      <div class="item">
        <a href="{{ produto.get_absolute_url }}">
          <img src="{% if produto.image %}{{ produto.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ produto.get_absolute_url }}"{{ produto.name }}></a>
        <br>
        ${{ produto.price}}
      </div>
      {% endfor %}
    </div>
    {% endblock %}